[package]
name = "thiserror_core2-impl"
version = "2.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>", "Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
rust-version = "1.31"
license = "MIT OR Apache-2.0"
description = "Implementation detail of the `thiserror_core2` crate"
repository = "https://github.com/bbqsrc/thiserror-core2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0.45"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
